version: "3"

services:
  cadvisor:
    restart: always
    image: gcr.io/google-containers/cadvisor:v0.36.0
    container_name: cadvisor
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      # Default location
      # - "/var/lib/docker/:/var/lib/docker:ro"
      # Snap location
      - "/var/snap/docker/current:/var/lib/docker:ro"
    expose:
      - "8080"
    ports:
      - 8085:8080

  prometheus:
    restart: always
    depends_on:
      - gcp-exporter
    image: prom/prometheus:v2.26.0
    container_name: prometheus
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PWD}/rules.yml:/etc/alertmanager/rules.yml
    expose:
      - "9090"
    ports:
      - 9090:9090

  alertmanager:
    restart: always
    depends_on:
      - prometheus
    image: prom/alertmanager:v0.21.0
    container_name: alertmanager
    volumes:
      - ${PWD}/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    expose:
      - "9093"
    ports:
      - 9093:9093

  gcp-exporter:
    image: ghcr.io/dazwilkin/gcp-exporter:5f45a64e9f0c2f37ace46671fe37ffa5917edecf
    container_name: gcp-exporter
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/client_secrets.json
    volumes:
      - ${HOME}/.config/gcloud/application_default_credentials.json:/secrets/client_secrets.json
    expose:
      - "9402" # GCP Exporter port registered on Prometheus Wiki
    ports:
      - 9402:9402
