version: "3"

services:
  cadvisor:
    restart: always
    image: gcr.io/google-containers/cadvisor:v0.36.0
    container_name: cadvisor
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      # Default location
      # - "/var/lib/docker/:/var/lib/docker:ro"
      # Snap location
      - "/var/snap/docker/current:/var/lib/docker:ro"
    expose:
      - "8080"
    ports:
      - 8085:8080

  prometheus:
    restart: always
    depends_on:
      - gcp-exporter
    image: prom/prometheus:v2.26.0
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      # Permits `curl --request POST http://localhost:9090/-/reload`
      - --web.enable-lifecycle
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PWD}/rules.yml:/etc/alertmanager/rules.yml
    expose:
      - "9090"
    ports:
      - 9090:9090

  alertmanager:
    restart: always
    depends_on:
      - prometheus
    image: prom/alertmanager:v0.21.0
    container_name: alertmanager
    volumes:
      - ${PWD}/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    expose:
      - "9093"
    ports:
      - 9093:9093

  gcp-exporter:
    image: ghcr.io/dazwilkin/gcp-exporter:257aae6a6d3911543a9c098f5de25fa7f67b869e
    container_name: gcp-exporter
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/client_secrets.json
    volumes:
      # Default location
      # - ${HOME}/.config/gcloud/application_default_credentials.json:/secrets/client_secrets.json
      # Using Snap will not resolve ${HOME} and requires fully resolved path
      - /home/userid/.config/gcloud/application_default_credentials.json:/secrets/client_secrets.json
    expose:
      - "9402"
    ports:
      - 9402:9402
