apiVersion: v1
kind: List
metadata: {}
items:
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: gcp-exporter
      name: gcp-exporter
    spec:
      selector:
        app: gcp-exporter
      ports:
        - name: metrics
          port: 9402
          targetPort: 9402
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      labels:
        app: gcp-exporter
      name: gcp-exporter
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: gcp-exporter
      template:
        metadata:
          labels:
            app: gcp-exporter
        spec:
          containers:
            - name: gcp-exporter
              image: ghcr.io/dazwilkin/gcp-exporter:4485f7168bef4d823e3803a087a42d7b8b31eb0e
              env:
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /secrets/client_secrets.json
              ports:
                - name: metrics
                  containerPort: 9402
              volumeMounts:
                - name: secrets
                  mountPath: /secrets
          restartPolicy: Always
          volumes:
            - name: secrets
              secret:
                secretName: gcp-exporter
  - kind: ServiceMonitor
    apiVersion: monitoring.coreos.com/v1
    metadata:
      name: gcp-exporter
      labels:
        app: gcp-exporter
    spec:
      selector:
        matchLabels:
          app: gcp-exporter
      endpoints:
        - port: metrics
