name: build-container

on:
  push:
    branches:
      - master

jobs:
  exporter:
    name: exporter
    runs-on: ubuntu-latest
    env:
      REPO: dazwilkin/gcp-exporter
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: docker/setup-buildx-action@v1
      - name: login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR }}
      - name: build-push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          push: true
      - name: revise README
        run: sed --in-place "s|${REPO}:[0-9a-f]\{40\}|${REPO}:${COMMIT}|g" ./docker-compose.yml
      - name: revise docker-compose
        run: sed --in-place "s|${REPO}:[0-9a-f]\{40\}|${REPO}:${COMMIT}|g" ./README.md
      - name: check for changes
        run: git status
      - name: stage changes
        run: git add .
      - name: commit changes
        run: git commit --message "GitHub Actions updating README and docker-compose.yml"
      - name: push changes
        run: git push origin master
