name: build-container

on:
  push:
    branches:
      - master

jobs:
  gcp-exporter:
    name: gcp-exporter
    runs-on: ubuntu-latest
    env:
      REPO: dazwilkin/gcp-exporter
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: docker/setup-buildx-action@v1
      - name: login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR }}
      - name: Get kernel version
        run: echo "VERSION=$(uname --kernel-release)" >> ${GITHUB_ENV}
      - name: build-push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            VERSION=${{ env.VERSION }}
            COMMIT=${{ github.sha }}
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          push: true
      - name: revise README|docker-compose
        run: |
          sed --in-place "s|${{ env.REPO }}:[0-9a-f]\{40\}|${{ env.REPO }}:${{ github.sha }}|g" ./docker-compose.yml
          more ./docker-compose.yaml
          sed --in-place "s|${{ env.REPO }}:[0-9a-f]\{40\}|${{ env.REPO }}:${{ github.sha }}|g" ./README.md
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add .
          git commit --message "GitHub Actions updating README and docker-compose.yml"
          git push origin master
