name: build

on:
  push:
    branches:
      - master

jobs:
  gcp-exporter:
    name: gcp-exporter
    runs-on: ubuntu-latest
    env:
      REPO: dazwilkin/gcp-exporter
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: docker/setup-buildx-action@v2
      - name: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR }}
      - name: Get kernel version
        run: echo "VERSION=$(uname --kernel-release)" >> ${GITHUB_ENV}
      - name: build-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            VERSION=${{ env.VERSION }}
            COMMIT=${{ github.sha }}
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          push: true
      - uses: sigstore/cosign-installer@main
      - name: Write signing key to disk (only needed for `cosign sign --key`)
        run: echo "${{ secrets.SIGNING }}" > ./cosign.key
      - name: Sign container image
        run: |
          cosign sign \
          --key=./cosign.key \
          --annotations="repo=${{ github.repository }}" \
          --annotations="workflow=${{ github.workflow }}" \
          --annotations="commit=${{ github.sha }}" \
          --annotations="version=${{ env.VERSION }}" \
          ghcr.io/${{ env.REPO }}:${{ github.sha }}
        env:
          COSIGN_PASSWORD: ""
      - name: revise occurrences of the image
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"

          for FILENAME in "./docker-compose.yml" "./kubernetes.yaml" "./README.md"
          do
            sed \
            --in-place \
            "s|ghcr.io/${{ env.REPO }}:[0-9a-f]\{40\}|ghcr.io/${{ env.REPO }}:${{ github.sha }}|g" \
            ${FILENAME}
            git add ${FILENAME}
          done

          git commit --message "GitHub Actions update image references"
          git push origin master
